services:
  scraping_service:
    build:
      context: ./src/services/scraping_service
      dockerfile: Dockerfile.scraping
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: always

  result_service:
    build:
      context: ./src/services/result_service
      dockerfile: Dockerfile.result
    ports:
      - "8001:8001"
    volumes:
      - ./data:/app/data
    restart: always

  preprocessing_training_service:
    build:
      context: ./src/services/preprocessing_training_service
      dockerfile: Dockerfile.preprocessing_training
    ports:
      - "8002:8002"
    volumes:
      - ./data:/app/data
      - ./pipeline:/app/pipeline
    restart: "no"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-data:
