global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "scraping_service"
    static_configs:
      - targets: ["scraping_service:8000"]

  - job_name: "result_service"
    static_configs:
      - targets: ["result_service:8001"]
